text=input("Please enter the text ")
l=len(text)
print('             {}'.format("_"*l))
print('           < {} >'.format(text))
print('             {}'.format("-"*l))
print('           /')
print(' /\_/\    /')
print('( o.o )')
print(' > ^ <')